name: sonathix_web
description: Site SONATHIX GROUP
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.6.0 <4.0.0"
  flutter: ">=3.27.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  supabase_flutter: ^2.8.0
  web: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
image_picker: ^1.1.2
flutter:
  uses-material-design: true

  # Décommentez et ajustez si vous utilisez des images/assets locaux dans votre site
  # assets:
  #   - assets/images/
  #   - assets/icons/
